export const ErrorCodes = {
  VALIDATION_FAILED: 'VALIDATION_FAILED',
  AUTHENTICATION_REQUIRED: 'AUTHENTICATION_REQUIRED',
  INVALID_CREDENTIALS: 'INVALID_CREDENTIALS',
  MISSING_PERMISSION: 'MISSING_PERMISSION',
  RESOURCE_NOT_FOUND: 'RESOURCE_NOT_FOUND',
  RESOURCE_CONFLICT: 'RESOURCE_CONFLICT',
  VERSION_CONFLICT: 'VERSION_CONFLICT',
  INVALID_PAGINATION: 'INVALID_PAGINATION',
  IDEMPOTENCY_KEY_REUSED: 'IDEMPOTENCY_KEY_REUSED',
  REQUEST_IN_PROGRESS: 'REQUEST_IN_PROGRESS',
  INTERNAL_SERVER_ERROR: 'INTERNAL_SERVER_ERROR',
  CANDIDATE_ALREADY_EXISTS: 'CANDIDATE_ALREADY_EXISTS',
  CANDIDATE_NOT_FOUND: 'CANDIDATE_NOT_FOUND',
  CANDIDATE_HAS_APPLICATIONS: 'CANDIDATE_HAS_APPLICATIONS',
  APPLICATION_ALREADY_EXISTS: 'APPLICATION_ALREADY_EXISTS',
  APPLICATION_NOT_FOUND: 'APPLICATION_NOT_FOUND',
  JOB_NOT_FOUND: 'JOB_NOT_FOUND',
  JOB_NOT_ACCEPTING_APPLICATIONS: 'JOB_NOT_ACCEPTING_APPLICATIONS',
  APPLICATION_STATE_CONFLICT: 'APPLICATION_STATE_CONFLICT',
  CV_NOT_FOUND: 'CV_NOT_FOUND',
  CV_FILE_REQUIRED: 'CV_FILE_REQUIRED',
  CV_FILE_INVALID: 'CV_FILE_INVALID',
  CV_FILE_TOO_LARGE: 'CV_FILE_TOO_LARGE',
  CV_STORAGE_ERROR: 'CV_STORAGE_ERROR',
  CV_PROFILE_NOT_READY: 'CV_PROFILE_NOT_READY',
  CV_PROFILE_LOCKED: 'CV_PROFILE_LOCKED',
  CV_VERSION_REFERENCED: 'CV_VERSION_REFERENCED',
  CV_PROFILE_NOT_APPROVED: 'CV_PROFILE_NOT_APPROVED',
  QUESTION_SET_NOT_FOUND: 'QUESTION_SET_NOT_FOUND',
  QUESTION_SET_ALREADY_APPROVED: 'QUESTION_SET_ALREADY_APPROVED',
  QUESTION_SET_NOT_EDITABLE: 'QUESTION_SET_NOT_EDITABLE',
  QUESTION_SET_STALE: 'QUESTION_SET_STALE',
  QUESTION_SET_EMPTY: 'QUESTION_SET_EMPTY',
  QUESTION_SET_INVALID_ITEMS: 'QUESTION_SET_INVALID_ITEMS',
  QUESTION_SET_SOURCE_INVALID: 'QUESTION_SET_SOURCE_INVALID',
  EVALUATION_CRITERION_NOT_FOUND: 'EVALUATION_CRITERION_NOT_FOUND',
  INTERVIEW_NOT_FOUND: 'INTERVIEW_NOT_FOUND',
  INTERVIEW_ALREADY_OPEN: 'INTERVIEW_ALREADY_OPEN',
  INTERVIEW_NOT_REVOCABLE: 'INTERVIEW_NOT_REVOCABLE',
  INTERVIEW_ALREADY_STARTED: 'INTERVIEW_ALREADY_STARTED',
  QUESTION_SET_NOT_APPROVED: 'QUESTION_SET_NOT_APPROVED',
  INVALID_INVITATION_EXPIRY: 'INVALID_INVITATION_EXPIRY',
  INVALID_INTERVIEW_DURATION: 'INVALID_INTERVIEW_DURATION',
  INVITATION_UNAVAILABLE: 'INVITATION_UNAVAILABLE',
  NOTIFICATION_NOT_FOUND: 'NOTIFICATION_NOT_FOUND',
  NOTIFICATION_NOT_RETRYABLE: 'NOTIFICATION_NOT_RETRYABLE',
  NOTIFICATION_SECRET_UNAVAILABLE: 'NOTIFICATION_SECRET_UNAVAILABLE',
  SESSION_NOT_STARTED: 'SESSION_NOT_STARTED',
  SESSION_EXPIRED: 'SESSION_EXPIRED',
  SESSION_CLOSED: 'SESSION_CLOSED',
  TURN_NOT_CURRENT: 'TURN_NOT_CURRENT',
  TURN_ALREADY_ANSWERED: 'TURN_ALREADY_ANSWERED',
  INVALID_ANSWER: 'INVALID_ANSWER',
  CONSENT_REQUIRED: 'CONSENT_REQUIRED',
  CONSENT_VERSION_MISMATCH: 'CONSENT_VERSION_MISMATCH',
  EARLY_FINISH_CONFIRMATION_REQUIRED: 'EARLY_FINISH_CONFIRMATION_REQUIRED',
} as const;

export type ErrorCode = (typeof ErrorCodes)[keyof typeof ErrorCodes];

export interface ApiError {
  code: string;
  message: string;
  requestId: string;
  details?: unknown;
}

export interface ApiErrorResponse {
  error: ApiError;
}
